spring:
  application:
    name: chess
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mariadb://localhost:3306/chess
    password: root
    username: root

#  data:
#    mongodb:
#      database: chess
#      password: root
#      host: mongodb+srv://root:${spring.data.mongodb.password}@chess.ialyzvk.mongodb.net/?retryWrites=true&w=majority
debug: off
